### ISSUE TITLE
`omnixrc` - needs to respect cached devshell

### ISSUE THREAD

**Issue by srid** [juspay/omnix#339]
It should not re-run health and other stuff when nix-direnv will be using the cached devshell. Otherwise there is perceptible delay every time we `cd` to the project dir.

![image](https://github.com/user-attachments/assets/01e24f0a-47f3-4a20-9864-7c8e7fa0e3cf)

**Comment by shivaraj-bh** [comment]
What if we have `omnix-direnv` like [nix-direnv](https://github.com/nix-community/nix-direnv)? `omnix-direnv` will provide custom `direnvrc` configuration to support `preShell` and `postShell`. In order to respect cached devShell we can use the same strategy as `nix-direnv` to cache the output of `nix print-dev-env`, see https://github.com/nix-community/nix-direnv/blob/7789681eb28fae8de052866f14d009f2375f9362/direnvrc#L335-L349. `omnix-direnv` will cache three devShells instead of just one. I haven’t completely thought this through, just wanted to put this idea out.

**Comment by srid** [comment]
Sufficiently resolved using YAML config.
